Models/ErrorViewModel.cs
namespace Caixai.Web2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AlunosController.cs
using Caixa;
using Caixai.Web2.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Caixai.Web2.Controllers
{
    public class AlunosController : Controller
    {
        private CaixaDbContext dbContext;

        public AlunosController(CaixaDbContext dbContext) 
        {
            this.dbContext = dbContext;
        }
        // GET: AlunosController
        public ActionResult Index()
        {
            return View(dbContext.Alunos);
        }
        

        // GET: AlunosController/Create
        public ActionResult Create()
        {
            ViewBag.Turmas = GetTurmas();
            return View();
        }
        private IEnumerable<SelectListItem> GetTurmas()
        {
            var turmas = dbContext.Turmas.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Nome }).ToList();
            turmas.Insert(0, new SelectListItem { Value = "", Text = "Selecione uma turma" });

            return turmas;
        }

        // POST: AlunosController/Create
        [HttpPost]
        public ActionResult Create(Aluno aluno)        
        {
            if (!ModelState.IsValid) 
            {
                ViewBag.Turmas = GetTurmas();
                return View(aluno);
            } 

            dbContext.Alunos.Add(aluno);
            dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: AlunosController/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (!id.HasValue) { return NotFound(); }

            var aluno = dbContext.Alunos.Find(id);
            if (aluno == null) { return NotFound(); }

            return View(aluno);
        }

        // POST: AlunosController/Edit/5
        [HttpPost]
        public ActionResult Edit(Aluno aluno)
        {
            dbContext.Alunos.Update(aluno);
            dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
                        
        }

        // GET: AlunosController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AlunosController/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/ErrosController.cs
using Microsoft.AspNetCore.Mvc;

namespace Caixai.Web2.Controllers
{
    public class ErrosController : Controller
    {
        [Route("Erros/Status/{code}")]
        public IActionResult status(int code)
        {
            if(code == 404) { return View("~/Views/Shared/Errors/NotFound.cshtml"); }
            return View();
        }
    }
}

Controllers/TurmasController.cs
using Caixa;
using Caixai.Web2.Data;
using Microsoft.AspNetCore.Mvc;

namespace Caixai.Web2.Controllers
{
    public class TurmasController : Controller
    {
        private readonly CaixaDbContext dbContext;
        public TurmasController(CaixaDbContext dbContext) => this.dbContext = dbContext;
        public IActionResult Index()
        {
            return View(dbContext.Turmas);
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Edit(Guid? id)
        {
            if(!id.HasValue) { return NotFound(); }

            var turma = dbContext.Turmas.Find(id);
            if(turma == null) {  return NotFound(); }

            return View(turma);
        }
        public IActionResult Delete(Guid? id)
        {
            if (!id.HasValue) { return NotFound(); }

            var turma = dbContext.Turmas.Find(id);
            if (turma == null) { return NotFound(); }



            return View(turma);
        }
        [HttpPost]
        public IActionResult Create(Turma turma)
        {
            if (!ModelState.IsValid)
            {
                return View(turma);
            }
            dbContext.Turmas.Add(turma);
            dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(Turma turma)
        {
            dbContext.Turmas.Update(turma);
            dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public IActionResult DeleteConfirm(Guid? id)
        {
            if (!id.HasValue) { return NotFound(); }

            var turma = dbContext.Turmas.Find(id);
            if (turma == null) { return NotFound(); }

            dbContext.Turmas.Remove(turma);
            dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Alunos/Create.cshtml
@model Caixai.Web2.Data.Aluno

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TurmaId" class="control-label"></label>
                <select asp-for="TurmaId" class ="form-control" asp-items="ViewBag.Turmas"></select>
                <span asp-validation-for="TurmaId" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Alunos/Edit.cshtml
@model Caixai.Web2.Data.Aluno

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TurmaId" class="control-label"></label>
                <select asp-for="TurmaId" class ="form-control" asp-items="ViewBag.Turmas"></select>
                <span asp-validation-for="TurmaId" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Alunos/Index.cshtml
@model IEnumerable<Caixai.Web2.Data.Aluno>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Cadastrar Novo Aluno</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turma)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(_ => item.Id)
            </td>
            <td>
                @Html.DisplayFor(_ => item.Name)
            </td>
            <td>
                @Html.DisplayFor(_ => item.Turma.Nome)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Caixai.Web2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Caixai.Web2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Turmas" asp-action="Index">Turmas CAIXAVERSO</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Turmas" asp-action="Index">Turmas</a>
                        </li>                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Caixai.Web2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Turmas/Create.cshtml
@using Caixai.Web2.Data

@model Turma

@{
    ViewData["Title"] = "Create Turma";
}

<h2 class="mb-4">Criar Turma</h2>
<div asp-validation-summary="All"></div>

<form asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control"/>
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Professor" class="form-label"></label>
        <input asp-for="Professor" class="form-control"/>
        <span asp-validation-for="Professor" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-primary">salvar</button>
    <a asp-action="Index" class="btn btn-secondary" ms-2>Cancelar</a>

</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Turmas/Delete.cshtml
@using Caixai.Web2.Data

@model Turma

@{
    ViewData["Title"] = "Delete Turma";
}

<h2 class="mb-4">Você tem certeza que deseja remover "@Model.Nome"?</h2>

<form asp-action="DeleteConfirm" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <input type="submit" value="Sim" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-primary">Cancelar</a>
    </div>
</form>

Views/Turmas/Edit.cshtml
@using Caixai.Web2.Data

@model Turma

@{
    ViewData["Title"] = "Edit Turma";
}

<h2 class="mb-4">Editar Turma</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control" required />
    </div>
    <div>
        <label asp-for="Professor" class="form-label"></label>
        <input asp-for="Professor" class="form-control" required />
    </div>
    <button type="submit" class="btn btn-primary">salvar</button>
    <a asp-action="Index" class="btn btn-secondary" ms-2>Cancelar</a>

    @section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }
</form>

Views/Turmas/Index.cshtml
@using Caixai.Web2.Data
@model IEnumerable<Turma>

<a asp-controller="Turmas" asp-action="Create" class="btn btn-primary">Cadastrar Nova Turma</a>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Id)</th>
        <th>@Html.DisplayNameFor(model => model.Nome)</th>
        <th>@Html.DisplayNameFor(model => model.Professor)</th>
        <th>Ações</th>
    </tr>

    @foreach(var turma in Model)
    {
        <tr>
            <td>@turma.Id</td>
            <td>@Html.DisplayFor(_ => turma.Nome)</td>
            <td>@Html.DisplayFor(_ => turma.Professor)</td>
            <td>
                <a asp-action="Edit" asp-route-id="@turma.Id" class="btn btn-info">Editar</a>
                <a asp-action="Delete" asp-route-id="@turma.Id" class="btn btn-danger">Deletar</a>
            </td>

        </tr>
    }
</table>